### ISSUE TITLE
Delete Method, 404

### ISSUE THREAD

**Issue by johnjazersalazar** [zakir-hyder/Citrix-GoToWebinar-PHP-Library#2]
Hello , I'm not sure if this is just on me, but I'm getting 404 error when I'm trying to delete a registrant via API. Though after several hours of looking into it, I resolved the issue, so I just want to share it, 
on line 311, you forgot to include the registrand_id variable. 
return $this->make_request("https://api.citrixonline.com/G2W/rest/organizers/".$this->organizer_key."/webinars/{$webinar_id}/registrants/{$registrant_id}", $params);

**Comment by johnjazersalazar** [comment]
also thank you guys for your awesome work.

**Comment by zakir-hyder** [comment]
@johnjazersalazar thank you. 
fixed with 079d134ed66506d1d1d3b7962f19e7d03674b5a7
